"""Stable identifier value objects.

Package 1 establishes the identifier convention only: opaque, prefixed,
URL-safe, generated by the application (never by the client).
"""

from __future__ import annotations

import re
import uuid
from dataclasses import dataclass
from typing import ClassVar, Self

from app.domain.errors import ValidationError

_SUFFIX_PATTERN = re.compile(r"^[0-9a-f]{32}$")


@dataclass(frozen=True, slots=True)
class EntityId:
    """Base for prefixed entity identifiers, e.g. ``wsp_2f6c...``."""

    prefix: ClassVar[str] = "ent"
    value: str

    def __post_init__(self) -> None:
        expected = f"{self.prefix}_"
        if not self.value.startswith(expected) or not _SUFFIX_PATTERN.match(
            self.value[len(expected) :]
        ):
            raise ValidationError(
                "malformed identifier", details={"expected_prefix": self.prefix}
            )

    @classmethod
    def generate(cls) -> Self:
        return cls(f"{cls.prefix}_{uuid.uuid4().hex}")

    @classmethod
    def parse(cls, raw: str) -> Self:
        return cls(raw)

    def __str__(self) -> str:
        return self.value


@dataclass(frozen=True, slots=True)
class WorkspaceId(EntityId):
    prefix: ClassVar[str] = "wsp"


@dataclass(frozen=True, slots=True)
class OrganizationId(EntityId):
    prefix: ClassVar[str] = "org"


@dataclass(frozen=True, slots=True)
class ProjectId(EntityId):
    prefix: ClassVar[str] = "prj"


@dataclass(frozen=True, slots=True)
class UserId(EntityId):
    prefix: ClassVar[str] = "usr"
